version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
      - .:/code
  #db:
      #image: mysql
      #ports:
        #- "3306:3306"
      #environment:
        #- MYSQL_ROOT_PASSWORD=password
        #- MYSQL_DATABASE=app_development
  redis:
    image: "redis:alpine"